apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z6kihhi8d-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d47ed0bc32eb0a46f6b960c18d9c41145bf7b5cf@sha256:61e6c67584864ebf2618f6aa30f6885490e5bf20b30be445f0bdb0d7f4369d00
          name: container-image
